### ISSUE TITLE
Helm charts for 3.0.0-alpha1 reference CRD v3 but deploys v2

### ISSUE THREAD

**Issue by ctron** [eclipse-iofog/helm#14]
The Helm charts for ioFog 3.0.0-alpha1 deploy a CRD version v2:

https://github.com/eclipse-iofog/helm/blob/7fc0f71ebb22c0062f7aabd371f6fb0f0d782a76/iofog/crds/crds.yml#L38-L42

But reference a version v3:

https://github.com/eclipse-iofog/helm/blob/7fc0f71ebb22c0062f7aabd371f6fb0f0d782a76/iofog/templates/control_plane.yml#L1-L2

This means, using the Helm charts is not possible.

**Comment by sergerad** [comment]
`apiVersion: iofog.org/v3` refers to the `iofogctl` YAML spec version. This is not the same as the Kubernetes CRD versions

**Comment by ctron** [comment]
But as you can see, you are referencing this in the Helm template. And the Helm charts fails do deploy:

~~~
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "ControlPlane" in version "iofog.org/v3"
~~~

**Comment by sergerad** [comment]
Have updated this in fcdc527ac8aed725bf8cfa4177cb7c14e29762c4
