### ISSUE TITLE
CRDs still use apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by ctron** [eclipse-iofog/helm#15]
The CRDs still use v1beta1, which is deprecated in Kubernetes 1.16 and removed in 1.22+ … 

Meaning: You can no longer install ioFog on the most recent Kubernetes version!

**Comment by sergerad** [comment]
Thanks @ctron have updated in fcdc527ac8aed725bf8cfa4177cb7c14e29762c4
