### ISSUE TITLE
Helm charts fail to deploy

### ISSUE THREAD

**Issue by ctron** [eclipse-iofog/helm#16]
Using the most recent change from `develop` I get:

~~~
Error: failed to install CRD crds/crds.yml: CustomResourceDefinition.apiextensions.k8s.io "applications.iofog.org" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[agent].properties[config].properties[changeFrequency].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[agent].properties[config].properties[deviceScanFrequency].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[agent].properties[config].properties[statusFrequency].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[config].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[container].properties[ports].items.properties[external].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[container].properties[ports].items.properties[internal].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[container].properties[ports].items.properties[publicPort].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[container].properties[rootHostAccess].type: Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[spec].properties[microservices].items.properties[rebuild].type: Required value: must not be empty for specified object fields]
~~~

**Comment by sergerad** [comment]
Looks like CI tests are giving false positives. Seems like the `iofog/crds` yamls are not being used. Will look into it

**Comment by sergerad** [comment]
I have updated develop and tested on `v1.18.20-gke.901` cluster.

Please note that our Helm project is much less used and tested than iofogctl which I would recommend for deploying ioFog on Kubernetes.

**Comment by ctron** [comment]
> Please note that our Helm project is much less used and tested than iofogctl 

I would recommend to set up an automated CI process for that: https://github.com/eclipse/packages/blob/master/.github/workflows/ci.yaml … with that, you can simply test this for a matrix of Kubernetes clusters.

> which I would recommend for deploying ioFog on Kubernetes.

"Helm" is standard tool to work with when it comes to Kubernetes, "iofogctl" is not. That is why IMHO the focus should be on Helm (or a tool like this), not on "iofog".

Additionally, in the Eclipse IoT Packages project (where we want to use this) Helm is the tool to use. As this is the common tool, supported by all other projects.

**Comment by ctron** [comment]
> I have updated develop and tested on `v1.18.20-gke.901` cluster.

I can go ahead and run the charts now. But there are permission issues now: https://github.com/eclipse-iofog/helm/issues/17 … did that work for you on GKE?
