### ISSUE TITLE
Helm 3.0 format not supported.

### ISSUE THREAD

**Issue by rouzikrm** [eclipse-iofog/helm#7]
When I try to apply iofog helm on kubernetes using Helm 3.0.2 it returns 
```manifest_sorter.go:175: info: skipping unknown hook: "crd-install"```
I fixed the issue by changing `crd-install` to pre-install in templates/crds.yml and replacing `apiVersion: apiextensions.k8s.io/v1beta1` by  `apiVersion: batch/v1` but still there is an issue with the Chart.yml telling `helm.go:76: [debug] validation: chart.metadata is required`.

would you please suggest a fix or work around for this issue?

**Comment by sergerad** [comment]
[v2.0.0](https://github.com/eclipse-iofog/helm/tree/v2.0.0) has added Helm 3 support
