### ISSUE TITLE
Allow installing without being cluster-admin

### ISSUE THREAD

**Issue by ctron** [eclipse-iofog/helm#9]
Currently the Helm chart binds the service account of the  ioFog operator to the role `cluster-admin`. That sounds overly excessive to me:

https://github.com/eclipse-iofog/helm/blob/120560f20e2cefa03e903e84e381f1d8b794a0c4/iofog/templates/operator.yml#L60-L63

The operator only watches a single namespace, so I would understand why it needs permissions for this single namespace.

Installing CRDs requires more access. However you can `--skip-crds` in Helm, or/and install the CRDs with an alternate user. The operator service account does not need access to that either.

I think it would be good to have an explicit list of permissions that are required, rather than "give me all".

**Comment by sergerad** [comment]
Cluster-admin was required due to Virtual Kubelet. Virtual Kubelet has been removed since v2.0.0 and so this can now be updated.
